/**
 * RFC 8439 conformance for ChaCha20-Poly1305, plus the XChaCha20 draft vector.
 *
 * These are the published vectors, not vectors generated by this code — the
 * whole point is that an implementation which agrees with itself proves
 * nothing. A cipher that passes here interoperates with every other correct
 * implementation, which is what "standard" has to mean.
 */

import {
  aeadDecrypt,
  aeadEncrypt,
  chacha20,
  chacha20Block,
  hchacha20,
  poly1305,
  timingSafeEqual,
  xaeadDecrypt,
  xaeadEncrypt,
} from "../js/chacha.js";

let failures = 0;
const hex = (bytes) => [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");
const unhex = (text) => Uint8Array.from(text.replace(/\s+/g, "").match(/../g).map((b) => parseInt(b, 16)));
const utf8 = (text) => new TextEncoder().encode(text);

function check(name, actual, expected) {
  const got = typeof actual === "string" ? actual : hex(actual);
  const want = typeof expected === "string" ? expected.replace(/\s+/g, "") : hex(expected);
  if (got === want) {
    console.log(`ok  ${name}`);
  } else {
    failures += 1;
    console.error(`FAIL ${name}\n  expected ${want}\n  got      ${got}`);
  }
}

function assert(name, condition) {
  if (condition) console.log(`ok  ${name}`);
  else {
    failures += 1;
    console.error(`FAIL ${name}`);
  }
}

/* --- RFC 8439 §2.3.2 — the block function --------------------------------- */

check(
  "block function (RFC 8439 2.3.2)",
  chacha20Block(
    unhex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"),
    1,
    unhex("000000090000004a00000000")
  ),
  "10f1e7e4d13b5915500fdd1fa32071c4c7d1f4c733c068030422aa9ac3d46c4e" +
    "d2826446079faa0914c2d705d98b02a2b5129cd1de164eb9cbd083e8a2503c4e"
);

/* --- RFC 8439 §2.4.2 — encryption ----------------------------------------- */

const SUNSCREEN =
  "Ladies and Gentlemen of the class of '99: If I could offer you only one tip for the future, sunscreen would be it.";

check(
  "chacha20 encryption (RFC 8439 2.4.2)",
  chacha20(
    unhex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"),
    unhex("000000000000004a00000000"),
    utf8(SUNSCREEN),
    1
  ),
  "6e2e359a2568f98041ba0728dd0d6981e97e7aec1d4360c20a27afccfd9fae0b" +
    "f91b65c5524733ab8f593dabcd62b3571639d624e65152ab8f530c359f0861d8" +
    "07ca0dbf500d6a6156a38e088a22b65e52bc514d16ccf806818ce91ab7793736" +
    "5af90bbf74a35be6b40b8eedf2785e42874d"
);

/* --- RFC 8439 §2.5.2 — Poly1305 ------------------------------------------- */

check(
  "poly1305 tag (RFC 8439 2.5.2)",
  poly1305(
    unhex("85d6be7857556d337f4452fe42d506a80103808afb0db2fd4abff6af4149f51b"),
    utf8("Cryptographic Forum Research Group")
  ),
  "a8061dc1305136c6c22b8baf0c0127a9"
);

/* --- RFC 8439 §2.8.2 — the AEAD ------------------------------------------- */

const AEAD_PLAIN = utf8(
  "Ladies and Gentlemen of the class of '99: If I could offer you only one tip for the future, sunscreen would be it."
);
const AEAD_AAD = unhex("50515253c0c1c2c3c4c5c6c7");
const AEAD_KEY = unhex("808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f");
const AEAD_NONCE = unhex("070000004041424344454647");

const sealed = aeadEncrypt(AEAD_KEY, AEAD_NONCE, AEAD_PLAIN, AEAD_AAD);

check(
  "aead ciphertext (RFC 8439 2.8.2)",
  sealed.subarray(0, sealed.length - 16),
  "d31a8d34648e60db7b86afbc53ef7ec2a4aded51296e08fea9e2b5a736ee62d6" +
    "3dbea45e8ca9671282fafb69da92728b1a71de0a9e060b2905d6a5b67ecd3b36" +
    "92ddbd7f2d778b8c9803aee328091b58fab324e4fad675945585808b4831d7bc" +
    "3ff4def08e4b7a9de576d26586cec64b6116"
);

check("aead tag (RFC 8439 2.8.2)", sealed.subarray(sealed.length - 16), "1ae10b594f09e26a7e902ecbd0600691");

check("aead round-trip", aeadDecrypt(AEAD_KEY, AEAD_NONCE, sealed, AEAD_AAD), AEAD_PLAIN);

/* --- Authentication must actually fail ------------------------------------ */

const tampered = Uint8Array.from(sealed);
tampered[4] ^= 0x01;
assert("tampered ciphertext is rejected", aeadDecrypt(AEAD_KEY, AEAD_NONCE, tampered, AEAD_AAD) === null);

const badTag = Uint8Array.from(sealed);
badTag[badTag.length - 1] ^= 0x80;
assert("tampered tag is rejected", aeadDecrypt(AEAD_KEY, AEAD_NONCE, badTag, AEAD_AAD) === null);

assert(
  "modified associated data is rejected",
  aeadDecrypt(AEAD_KEY, AEAD_NONCE, sealed, unhex("50515253c0c1c2c3c4c5c6c8")) === null
);

const wrongKey = Uint8Array.from(AEAD_KEY);
wrongKey[0] ^= 0xff;
assert("wrong key is rejected", aeadDecrypt(wrongKey, AEAD_NONCE, sealed, AEAD_AAD) === null);

const wrongNonce = Uint8Array.from(AEAD_NONCE);
wrongNonce[0] ^= 0xff;
assert("wrong nonce is rejected", aeadDecrypt(AEAD_KEY, wrongNonce, sealed, AEAD_AAD) === null);

assert("truncated input is rejected", aeadDecrypt(AEAD_KEY, AEAD_NONCE, sealed.subarray(0, 8), AEAD_AAD) === null);

/* --- HChaCha20 (draft-irtf-cfrg-xchacha §2.2.1) ---------------------------- */

check(
  "hchacha20 subkey",
  hchacha20(
    unhex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"),
    unhex("000000090000004a0000000031415927")
  ),
  "82413b4227b27bfed30e42508a877d73a0f9e4d58a74a853c12ec41326d3ecdc"
);

/* --- XChaCha20-Poly1305 round-trips --------------------------------------- */

/** getRandomValues caps at 64 KiB per call, so fill anything larger in chunks. */
function randomBytes(size) {
  const out = new Uint8Array(size);
  for (let offset = 0; offset < size; offset += 65536) {
    crypto.getRandomValues(out.subarray(offset, Math.min(offset + 65536, size)));
  }
  return out;
}

{
  const key = crypto.getRandomValues(new Uint8Array(32));
  const nonce = crypto.getRandomValues(new Uint8Array(24));
  const aad = utf8("cousin-congress/v2");
  for (const size of [0, 1, 15, 16, 17, 63, 64, 65, 1024, 65537, 200000]) {
    const plain = randomBytes(size);
    const box = xaeadEncrypt(key, nonce, plain, aad);
    const open = xaeadDecrypt(key, nonce, box, aad);
    if (!open || !timingSafeEqual(open, plain)) {
      failures += 1;
      console.error(`FAIL xchacha round-trip at ${size} bytes`);
    }
  }
  console.log("ok  xchacha20-poly1305 round-trips across sizes 0..65537");
}

/* --- Empty and edge inputs ------------------------------------------------ */

{
  const key = new Uint8Array(32).fill(7);
  const nonce = new Uint8Array(12).fill(9);
  const box = aeadEncrypt(key, nonce, new Uint8Array(0), new Uint8Array(0));
  assert("empty plaintext seals to just a tag", box.length === 16);
  const open = aeadDecrypt(key, nonce, box, new Uint8Array(0));
  assert("empty plaintext opens", open !== null && open.length === 0);
}

/* --- Counter rollover across many blocks ---------------------------------- */

{
  const key = new Uint8Array(32).fill(3);
  const nonce = new Uint8Array(12).fill(4);
  const long = new Uint8Array(64 * 300);
  const enc = chacha20(key, nonce, long, 1);
  const dec = chacha20(key, nonce, enc, 1);
  assert("300-block stream is its own inverse", timingSafeEqual(dec, long));
  // Distinct blocks must not repeat keystream.
  assert(
    "keystream differs between blocks",
    hex(enc.subarray(0, 64)) !== hex(enc.subarray(64, 128))
  );
}

assert("timingSafeEqual rejects different lengths", !timingSafeEqual(new Uint8Array(4), new Uint8Array(5)));

console.log(failures ? `\n${failures} FAILURES` : "\nchacha: all RFC 8439 vectors and round-trips pass");
process.exit(failures ? 1 : 0);
